App/urls.py
from django.conf.urls import url
from django.urls import path
from App import views

app_name = "App"

urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/', views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>/', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>/',views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/',views.edit_album, name='edit_album'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete_artist/<int:artist_id>/', views.delete_musician,name='delete_artist')
]

Musician/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models

# Create your models here.

class Musician(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=100)
    instrument = models.CharField(max_length = 50)

    def __str__(self):
        return self.first_name + " " + self.last_name


class  Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    release_date = models.DateTimeField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent!"),
    )

    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating " + str(self.num_stars) 
        

App/forms.py
from django import forms
from App import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

App/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from App.models import Musician, Album
from App import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title' : 'Home Page', 'musician_list':musician_list}
    return render(request, 'App/index.html', context=diction)


def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name','release_date')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))

    diction = {'title': 'List of albums', 'artist_info':artist_info, 'album_list':album_list, 'artist_rating':artist_rating}
    return render ( request, 'App/album_list.html', context=diction) 


def musician_form(request):
    form = forms.MusicianForm()

    if request.method == "POST":
        form = forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': 'Add Musician', 'musician_form': form}
    return render ( request, 'App/musician_form.html', context=diction)

def album_form(request):
    form = forms.AlbumForm()

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': 'Add Album', 'album_form': form}
    return render ( request, 'App/album_form.html', context=diction)

def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=artist_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)

    diction = {'edit_form':form}
    return render ( request, 'App/edit_artist.html', context=diction)  


def edit_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    form =forms.AlbumForm(instance=album_info)
    diction = {}

    if request.method =="POST":
        form = forms.AlbumForm(request.POST, instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':'Successfully Updated!'})

    diction.update({'edit_form':form})
    diction.update({'album_id': album_id})
    return render(request, 'App/edit_album.html', context=diction)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction={'delete_success':'Album Delete Successfully!!'}
    return render ( request,'App/delete.html', context=diction)

def delete_musician(request, artist_id):
    artist = Musician.objects.get(pk=artist_id).delete(0)
    diction={'delete_success':'Musician Delete Successfully!!'}
    return render ( request,'App/delete.html',context=diction)

templates/App/album_form.html
{% extends 'App/base.html' %}

{% block body_block %}
<h3>Album form:</h3>

<form method="POST">
    {{ album_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Music" class="btn btn-primary btn-sm">
</form>

{% endblock %}

templates/App/album_list.html
{% extends 'App/base.html' %}

{% block body_block %}

<h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }} </h4>
<h4>instrument: {{ artist_info.instrument}}</h4> 
<h4>Artist Rating: {{ artist_rating.num_stars__avg }}</h4>
<a href="{% url 'App:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary btn-sm">Edit</a>
<h3>list of Album </h3>
<hr>
<table class="table table-bordered">
    <tr>
        <th>Album Name </th>
        <th>Release Date</th>
        <th>Rating</th>
    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{% url 'App:edit_album' album_id=album.id %}">{{ album.name }}</a></td>
        <td>{{ album.release_date|date:"M d, Y" }}</td>
        <td>{{ album.num_stars }}</td>
    </tr>
    {% endfor %}
</table>
<br>

<a href="{% url 'App:delete_artist' artist_id=artist_info.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete Musician?')">Delete</a>
{% endblock %}

templates/App/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{{ title }}</title>

  </head>
  <body>
    <nav class ="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App:index' %}">Home</a>
            </li>
  
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App:musician_form' %}">Add Musician</a>
            </li>

            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App:album_form' %}">Add Album</a>
            </li>

        </ul>

    </nav>



    <div class="container">
        {% block body_block %}
        
        
        {% endblock %}
    </div>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/App/delete.html
{% extends 'App/base.html' %}
{% block body_block %}

<div class="alert alert-danger">{{ delete_success }}</div>

{% endblock %}

templates/App/edit_album.html
{% extends 'App/base.html' %}
{% block body_block %}
<h4>Edit Album</h4>
{% if success_text %}

<div class="alert alert-success">
    {{ success_text }}
</div>

{% endif %}
<form method="POST">
    {{ edit_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-primary btn-sm">
</form>

<br>
<a href="{% url 'App:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album?')">Delete</a>

{% endblock %}

templates/App/edit_artist.html
{% extends 'App/base.html' %}
{% block body_block %}
<h4>Edit Artist</h4>

<form method="POST">
    {{ edit_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-md">
</form>

{% endblock %}

templates/App/index.html
{% extends 'App/base.html' %}

{% block body_block %}

<h3>List of Musicians: </h3>
<ul>
    {% if musician_list %}
    {% for musician in musician_list %}
        <li> <a href="{% url 'App:album_list' artist_id=musician.id %}"> {{ musician.first_name }} {{ musician.last_name }}</a> </li>

    {% endfor %}
    {% else %}
    <h4>No Musician in the list</h4>
    {% endif %}
</ul>
{% endblock %}

templates/App/musician_form.html
{% extends 'App/base.html' %}
{% block body_block %}
<h3>musician form:</h3>

<form method="POST">
    {{ musician_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Music" class="btn btn-primary btn-sm">
</form>

{% endblock %}